server:
  port: 8083


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/osonsugurta
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  mvc:
    cors:
      mappings:
        /**:
          allowed-origins: "*"
          allowed-methods: "*"
          allowed-headers: "*"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none


jwt:
  expiry: 604800000
  secret: qwetuykyjhfdgsafgjhkoiutrefdsavzbxcnmktjyhretgwedfvbnjkrjyerhsfg





